### ISSUE TITLE
Il sistema è stato disattivato?

### ISSUE THREAD

**Issue by Wasureta333** [Gabboxl/gtt-api-keygen#1]
Ciao! 
Premetto subito che sono alle prime armi con le API.
Per il progetto che sto seguendo vorrei provare a implementare in un applicazione(powerapps) le api della gtt, che ho capito
essere estremamente accessibili grazie a te.
Però in questo momento ogni chiamata sembra non funzionare.
Cosa posso fare? è stato interrotto tutto o ho interpretato male? grazie mille

**Comment by Gabboxl** [comment]
Ciao!
Purtroppo è come dici tu, dopo l'uscita della nuova app "MATO" GTT è passata all'utilizzo di altre API chiudendo l'accesso a questa. 
Non ho più avuto tempo di aggiornare questo progetto, però sono a conoscenza di questa app Android (https://github.com/valerio-bozzolan/bus-torino) che utilizza queste nuove API per visualizzare i dati. 
Dovrebbero essere altrettanto semplici da usare, soltanto che nessuno le ha documentate in pubblico per bene al momento.

Se hai altre domande chiedi pure : )

**Comment by Wasureta333** [comment]
grazie di cuore!

Il giorno mer 15 feb 2023 alle ore 21:32 Gabriele ***@***.***>
ha scritto:

**Comment by Gabboxl** [comment]
Di niente : )
